const mockData = [
    { studentId: 'SV001', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV002', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV003', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV004', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV005', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV006', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV007', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV008', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV009', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV0010', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV0011', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV0012', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV0013', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV0014', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV0020', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV0030', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV0015', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV0021', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV0031', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV0016', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV0024', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV0033', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV0017', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV0023', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV0032', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV0018', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV0026', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    { studentId: 'SV0037', aiGrade: 7, teacherGrade: 9, averageGrade: 10 },
    { studentId: 'SV0019', aiGrade: 8, teacherGrade: 7.5, averageGrade: 6 },
    { studentId: 'SV0029', aiGrade: 9, teacherGrade: 8, averageGrade: 7 },
    // Add more mock data...
  ];